
#   express:
#     image: node:16
#     build: ./backend
#     ports:
#       - "3000:8000"
#     links:
#       - frotend
#   frotend:

version: "3.9"

services:
    express:
        build: ./backend
        # volums:
        #     - ${HOME_CLOUD_STORAGE}:/usr/src/app/storage
        # environment: 
        #     HOME_CLOUD_STORAGE: /usr/src/app/storage
        #     NODE_ENV: production
        ports:
            - "3000:8000"

